# Generated by Django 4.2.5 on 2023-10-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediCareHub', '0003_pharmacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='name',
            new_name='medicine',
        ),
    ]
